2025-04-15 22:07:39,574 ERROR: Exception on /contact [GET] [in /home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/app/routes.py", line 52, in contact
    return render_template('contact.html', form=form)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/templating.py", line 149, in render_template
    template = app.jinja_env.get_or_select_template(template_name_or_list)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1087, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/environment.py", line 1016, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/hkpqw/Рабочий стол/diplomPMK/app/templates/contact.html", line 70, in template
    {% endif %}
jinja2.exceptions.TemplateSyntaxError: Unexpected end of template. Jinja was looking for the following tags: 'endblock'. The innermost block that needs to be closed is 'block'.
2025-04-15 22:08:09,799 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:13:31,442 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:14:55,721 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:15:43,210 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:16:30,640 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:17:51,636 ERROR: Exception on /service/1 [GET] [in /home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask_login/utils.py", line 285, in decorated_view
    return current_app.login_manager.unauthorized()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask_login/login_manager.py", line 196, in unauthorized
    redirect_url = make_login_url(login_view, next_url=request.url)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask_login/utils.py", line 120, in login_url
    base = expand_login_view(login_view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask_login/utils.py", line 97, in expand_login_view
    return url_for(login_view)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/helpers.py", line 232, in url_for
    return current_app.url_for(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 1121, in url_for
    return self.handle_url_build_error(error, endpoint, values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/flask/app.py", line 1110, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hkpqw/Рабочий стол/diplomPMK/venv/lib/python3.12/site-packages/werkzeug/routing/map.py", line 924, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'login'. Did you mean 'main.login' instead?
2025-04-15 22:20:05,209 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:20:10,881 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
2025-04-15 22:20:30,706 INFO: PMK212 startup [in /home/hkpqw/Рабочий стол/diplomPMK/app/__init__.py:46]
